name: CI
on: [push, pull_request]
jobs:
  checks:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile --ignore-scripts
      - run: pnpm run prettier:check
      - run: pnpm run lint:check
#  tests:
#    name: Tests
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: ['lts/*', 'latest']
#      fail-fast: false
#    steps:
#      - uses: actions/checkout@v3
#      - uses: pnpm/action-setup@v3
#        with:
#          version: 8
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'pnpm'
#      - run: pnpm i --frozen-lockfile --ignore-scripts
#      - run: pnpm run test:ci
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile --ignore-scripts
      - run: pnpm build